Repository edwindelbosque/Cowboys-vs-Aliens, pull requests merged in 2019-09, with the labels that each got.

#5 Add a couple methods to Round class file and fix indentations
  data/surveys.js
  src/DominationRound.js
  src/Game.js
  src/Player.js
  src/Round.js
  test/round-test.js
Labels: enhancement

#6 Add basic alignment to DOM
  src/css/base.scss
  src/index.html
Labels: enhancement

#7 Add startpage for the game and SASS styling and animations
  src/.DS_Store
  src/css/base.scss
  src/images/alien-icon.png
  src/images/cowboy-icon.png
  src/images/favicon-16x16.png
  src/images/favicon-32x32.png
  src/images/grainy-filter-2.png
  src/images/grainy-filter.jpg
  src/images/start-page.gif
  src/index.html
  src/index.js
Labels: enhancement

#9 Game class start
  src/DominationRound.js
  src/Game.js
  src/Player.js
  src/Round.js
  test/fast-money-test.js
  test/game-test.js
  test/round-test.js
Labels: enhancement

#12 Add scroll animation from start page to main game and vice-versa
  src/css/base.scss
  src/images/grainy-filter-2.png
  src/images/grainy-filter.jpg
  src/images/turing-logo.png
  src/index.html
  src/index.js
Labels: enhancement

#13 Restructure files to be connected
  src/Game.js
  src/Player.js
  src/Round.js
  src/Turn.js
  test/game-test.js
  test/player-test.js
  test/round-test.js
  test/turn-test.js
Labels: bug

#14 Add styling and hover animations to both sections of game
  src/css/base.scss
  src/index.html
Labels: enhancement

#15 Add spice test file for scripts.js
  src/css/base.scss
  src/index.html
  test/scripts-test.js
Labels: documentation, help wanted

#22 Add more DOM functionality
  src/css/base.scss
  src/index.html
  src/index.js
Labels: enhancement

#27 Fetch data and debugging
  src/DOMupdates.js
  src/DominationTurn.js
  src/Game.js
  src/Round.js
  src/Turn.js
  src/css/_animations.scss
  src/css/_round-page.scss
  src/css/_start-page.scss
  src/css/_variables.scss
  src/css/base.scss
  src/index.js
  test/round-test.js
  test/turn-test.js
Labels: enhancement

#29 Edb toggle improvement
  src/DOMupdates.js
  src/Game.js
  src/Round.js
  src/Turn.js
  src/index.js
  test/DominationTurn-test.js
  test/turn-test.js
Labels: enhancement

#41 Cherry pick Eric's working commits for PR
  src/DOMupdates.js
  src/DominationRound.js
  src/DominationTurn.js
  src/Game.js
  src/RegularRound.js
  src/RegularTurn.js
  src/Round.js
  src/Turn.js
  src/index.html
  src/index.js
Labels: enhancement

#43 Domination round 1
  src/DOMupdates.js
  src/DominationRound.js
  src/DominationTurn.js
  src/Game.js
  src/RegularRound.js
  src/RegularTurn.js
  src/Turn.js
  src/css/_round-page.scss
  src/index.html
  src/index.js
Labels: enhancement

#44 Add custom cursor design for game
  src/css/base.scss
Labels: enhancement

#46 Give feedback and toggle multiplier-input/input-guess
  src/DOMupdates.js
  src/RegularTurn.js
  src/Turn.js
  src/css/_round-page.scss
  src/index.html
  src/index.js
Labels: enhancement

#48 Display winner when game finishes
  src/DOMupdates.js
  src/Game.js
  src/index.js
Labels: enhancement

#50 Adds visual feedback to Domination Turns and refreshes page on exit b…
  src/DominationTurn.js
  src/index.html
  src/index.js
Labels: enhancement

#52 Improve experience from UI/UX user testing
  src/DOMupdates.js
  src/RegularTurn.js
  src/Round.js
  src/css/_round-page.scss
  src/css/base.scss
Labels: enhancement
